WITH raw_data AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY PRODUCT_ID, STORE_ID, WEEK_NO
            ORDER BY PRODUCT_ID
        ) AS row_num
    FROM {{ source('raw', 'CAUSAL_DATA') }}
    WHERE PRODUCT_ID IS NOT NULL
      AND STORE_ID IS NOT NULL
      AND WEEK_NO IS NOT NULL
),

deduplicated AS (
    SELECT * FROM raw_data WHERE row_num = 1
)

SELECT
    PRODUCT_ID,
    STORE_ID,
    WEEK_NO,
    COALESCE(DISPLAY, '0') AS DISPLAY,
    COALESCE(MAILER, '0') AS MAILER,
    CASE WHEN COALESCE(DISPLAY, '0') != '0' THEN TRUE ELSE FALSE END AS HAS_DISPLAY,
    CASE WHEN COALESCE(MAILER, '0') != '0' THEN TRUE ELSE FALSE END AS HAS_MAILER,
    CASE WHEN COALESCE(DISPLAY, '0') != '0' OR COALESCE(MAILER, '0') != '0' THEN TRUE ELSE FALSE END AS IS_PROMOTED,
    CASE
        WHEN COALESCE(DISPLAY, '0') != '0' AND COALESCE(MAILER, '0') != '0' THEN 'DISPLAY_AND_MAILER'
        WHEN COALESCE(DISPLAY, '0') != '0' THEN 'DISPLAY_ONLY'
        WHEN COALESCE(MAILER, '0') != '0' THEN 'MAILER_ONLY'
        ELSE 'NO_PROMO'
    END AS PROMO_TYPE
FROM deduplicated
WHERE WEEK_NO BETWEEN 1 AND 102
