WITH raw_data AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY HOUSEHOLD_KEY, BASKET_ID, PRODUCT_ID, DAY
            ORDER BY TRANS_TIME
        ) AS row_num
    FROM {{ source('raw', 'TRANSACTION_DATA') }}
    WHERE HOUSEHOLD_KEY IS NOT NULL
      AND PRODUCT_ID IS NOT NULL
      AND BASKET_ID IS NOT NULL
      AND SALES_VALUE IS NOT NULL
),

deduplicated AS (
    SELECT * FROM raw_data WHERE row_num = 1
),

with_calculations AS (
    SELECT
        HOUSEHOLD_KEY,
        BASKET_ID,
        DAY,
        PRODUCT_ID,
        CASE WHEN QUANTITY <= 0 THEN 1 ELSE QUANTITY END AS QUANTITY,
        SALES_VALUE,
        STORE_ID,
        COALESCE(RETAIL_DISC, 0) AS RETAIL_DISC,
        TRANS_TIME,
        WEEK_NO,
        COALESCE(COUPON_DISC, 0) AS COUPON_DISC,
        COALESCE(COUPON_MATCH_DISC, 0) AS COUPON_MATCH_DISC,
        COALESCE(RETAIL_DISC, 0) + COALESCE(COUPON_DISC, 0) + COALESCE(COUPON_MATCH_DISC, 0) AS TOTAL_DISCOUNT,
        SALES_VALUE + COALESCE(RETAIL_DISC, 0) + COALESCE(COUPON_DISC, 0) + COALESCE(COUPON_MATCH_DISC, 0) AS GROSS_PRICE,
        CASE
            WHEN COALESCE(RETAIL_DISC, 0) > 0 OR COALESCE(COUPON_DISC, 0) > 0 OR COALESCE(COUPON_MATCH_DISC, 0) > 0
            THEN TRUE ELSE FALSE
        END AS IS_DISCOUNTED
    FROM deduplicated
),

outlier_bounds AS (
    SELECT
        PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY SALES_VALUE) AS sales_p99,
        PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY QUANTITY) AS qty_p99
    FROM with_calculations
)

SELECT
    c.HOUSEHOLD_KEY,
    c.BASKET_ID,
    c.DAY,
    c.PRODUCT_ID,
    c.QUANTITY,
    c.SALES_VALUE,
    c.STORE_ID,
    c.RETAIL_DISC,
    c.TRANS_TIME,
    c.WEEK_NO,
    c.COUPON_DISC,
    c.COUPON_MATCH_DISC,
    c.TOTAL_DISCOUNT,
    c.GROSS_PRICE,
    c.IS_DISCOUNTED,
    CASE WHEN c.SALES_VALUE > ob.sales_p99 OR c.QUANTITY > ob.qty_p99 THEN TRUE ELSE FALSE END AS IS_OUTLIER,
    CASE WHEN c.DAY BETWEEN 1 AND 711 THEN TRUE ELSE FALSE END AS IS_VALID_DAY,
    CASE WHEN c.WEEK_NO BETWEEN 1 AND 102 THEN TRUE ELSE FALSE END AS IS_VALID_WEEK
FROM with_calculations c
CROSS JOIN outlier_bounds ob
WHERE c.SALES_VALUE > 0
