SELECT
    DESCRIPTION AS CAMPAIGN_TYPE,
    CAMPAIGN AS CAMPAIGN_ID,
    START_DAY,
    END_DAY,
    END_DAY - START_DAY AS CAMPAIGN_DURATION_DAYS,
    CASE WHEN START_DAY >= END_DAY THEN TRUE ELSE FALSE END AS IS_INVALID_DATE_RANGE,
    CASE WHEN START_DAY BETWEEN 1 AND 711 AND END_DAY BETWEEN 1 AND 711 THEN TRUE ELSE FALSE END AS IS_VALID_PERIOD
FROM {{ source('raw', 'CAMPAIGN_DESC') }}
WHERE CAMPAIGN IS NOT NULL
  AND START_DAY IS NOT NULL
  AND END_DAY IS NOT NULL
