WITH raw_data AS (
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY HOUSEHOLD_KEY ORDER BY HOUSEHOLD_KEY) AS row_num
    FROM {{ source('raw', 'HH_DEMOGRAPHIC') }}
    WHERE HOUSEHOLD_KEY IS NOT NULL
),

deduplicated AS (
    SELECT * FROM raw_data WHERE row_num = 1
)

SELECT
    HOUSEHOLD_KEY,
    COALESCE(AGE_DESC, 'UNKNOWN') AS AGE_DESC,
    COALESCE(MARITAL_STATUS_CODE, 'U') AS MARITAL_STATUS_CODE,
    COALESCE(INCOME_DESC, 'UNKNOWN') AS INCOME_DESC,
    COALESCE(HOMEOWNER_DESC, 'UNKNOWN') AS HOMEOWNER_DESC,
    COALESCE(HH_COMP_DESC, 'UNKNOWN') AS HH_COMP_DESC,
    COALESCE(HOUSEHOLD_SIZE_DESC, 'UNKNOWN') AS HOUSEHOLD_SIZE_DESC,
    COALESCE(KID_CATEGORY_DESC, 'UNKNOWN') AS KID_CATEGORY_DESC,
    CASE
        WHEN AGE_DESC IS NULL OR INCOME_DESC IS NULL OR MARITAL_STATUS_CODE IS NULL
        THEN TRUE ELSE FALSE
    END AS HAS_MISSING_DEMOGRAPHICS
FROM deduplicated
