WITH raw_data AS (
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY PRODUCT_ID) AS row_num
    FROM {{ source('raw', 'PRODUCT') }}
    WHERE PRODUCT_ID IS NOT NULL
),

deduplicated AS (
    SELECT * FROM raw_data WHERE row_num = 1
)

SELECT
    PRODUCT_ID,
    MANUFACTURER,
    COALESCE(UPPER(TRIM(DEPARTMENT)), 'UNKNOWN') AS DEPARTMENT,
    COALESCE(UPPER(TRIM(BRAND)), 'UNKNOWN') AS BRAND,
    COALESCE(UPPER(TRIM(COMMODITY_DESC)), 'UNKNOWN') AS COMMODITY_DESC,
    COALESCE(UPPER(TRIM(SUB_COMMODITY_DESC)), 'UNKNOWN') AS SUB_COMMODITY_DESC,
    TRIM(CURR_SIZE_OF_PRODUCT) AS CURR_SIZE_OF_PRODUCT,
    CASE WHEN DEPARTMENT IS NULL OR BRAND IS NULL THEN TRUE ELSE FALSE END AS HAS_MISSING_DATA
FROM deduplicated
