WITH household_rfm AS (
    SELECT
        HOUSEHOLD_KEY,
        MAX(DAY) AS LAST_PURCHASE_DAY,
        COUNT(DISTINCT BASKET_ID) AS FREQUENCY,
        SUM(SALES_VALUE) AS MONETARY
    FROM {{ ref('stg_transactions') }}
    GROUP BY 1
),

rfm_scored AS (
    SELECT
        *,
        711 - LAST_PURCHASE_DAY AS RECENCY,
        NTILE(4) OVER (ORDER BY 711 - LAST_PURCHASE_DAY DESC) AS R_SCORE,
        NTILE(4) OVER (ORDER BY FREQUENCY ASC) AS F_SCORE,
        NTILE(4) OVER (ORDER BY MONETARY ASC) AS M_SCORE
    FROM household_rfm
),

segmented AS (
    SELECT
        *,
        CASE
            WHEN F_SCORE >= 3 AND M_SCORE >= 3 THEN 'Champions'
            WHEN F_SCORE >= 3 AND M_SCORE < 3 THEN 'Loyal Customers'
            WHEN R_SCORE <= 2 AND F_SCORE >= 2 THEN 'Recent Customers'
            ELSE 'At Risk'
        END AS CUSTOMER_SEGMENT
    FROM rfm_scored
),

txn_with_promo AS (
    SELECT
        t.HOUSEHOLD_KEY,
        t.SALES_VALUE,
        t.TOTAL_DISCOUNT,
        t.IS_DISCOUNTED,
        COALESCE(c.IS_PROMOTED, FALSE) AS IS_PROMOTED
    FROM {{ ref('stg_transactions') }} t
    LEFT JOIN {{ ref('stg_causal') }} c
        ON t.PRODUCT_ID = c.PRODUCT_ID
        AND t.STORE_ID = c.STORE_ID
        AND t.WEEK_NO = c.WEEK_NO
    WHERE t.IS_OUTLIER = FALSE
)

SELECT
    s.CUSTOMER_SEGMENT,
    COUNT(DISTINCT s.HOUSEHOLD_KEY) AS NUM_HOUSEHOLDS,
    ROUND(AVG(s.RECENCY), 1) AS AVG_RECENCY,
    ROUND(AVG(s.FREQUENCY), 1) AS AVG_FREQUENCY,
    ROUND(AVG(s.MONETARY), 2) AS AVG_MONETARY,
    ROUND(SUM(CASE WHEN tp.IS_PROMOTED THEN tp.SALES_VALUE ELSE 0 END) /
          NULLIF(SUM(tp.SALES_VALUE), 0) * 100, 2) AS PROMO_SPEND_PCT,
    ROUND(AVG(CASE WHEN tp.IS_PROMOTED THEN tp.SALES_VALUE END), 2) AS AVG_PROMO_TRANSACTION,
    ROUND(AVG(CASE WHEN NOT tp.IS_PROMOTED THEN tp.SALES_VALUE END), 2) AS AVG_NON_PROMO_TRANSACTION,
    CASE
        WHEN AVG(CASE WHEN NOT tp.IS_PROMOTED THEN tp.SALES_VALUE END) > 0
        THEN ROUND(
            (AVG(CASE WHEN tp.IS_PROMOTED THEN tp.SALES_VALUE END) -
             AVG(CASE WHEN NOT tp.IS_PROMOTED THEN tp.SALES_VALUE END)) /
            AVG(CASE WHEN NOT tp.IS_PROMOTED THEN tp.SALES_VALUE END) * 100, 2)
        ELSE NULL
    END AS PROMO_LIFT_BY_SEGMENT_PCT,
    ROUND(AVG(CASE WHEN tp.IS_DISCOUNTED THEN tp.TOTAL_DISCOUNT END), 2) AS AVG_DISCOUNT_TAKEN
FROM segmented s
JOIN txn_with_promo tp ON s.HOUSEHOLD_KEY = tp.HOUSEHOLD_KEY
GROUP BY 1
