WITH campaign_households AS (
    SELECT
        ct.CAMPAIGN,
        cd.CAMPAIGN_TYPE,
        cd.START_DAY,
        cd.END_DAY,
        cd.CAMPAIGN_DURATION_DAYS,
        ct.HOUSEHOLD_KEY
    FROM {{ source('raw', 'CAMPAIGN_TABLE') }} ct
    JOIN {{ ref('stg_campaigns') }} cd ON ct.CAMPAIGN = cd.CAMPAIGN_ID
),

campaign_txns AS (
    SELECT
        ch.CAMPAIGN,
        ch.CAMPAIGN_TYPE,
        ch.CAMPAIGN_DURATION_DAYS,
        ch.HOUSEHOLD_KEY,
        SUM(CASE WHEN t.DAY BETWEEN ch.START_DAY AND ch.END_DAY THEN t.SALES_VALUE ELSE 0 END) AS DURING_CAMPAIGN_SPEND,
        SUM(CASE WHEN t.DAY BETWEEN ch.START_DAY - ch.CAMPAIGN_DURATION_DAYS AND ch.START_DAY - 1 THEN t.SALES_VALUE ELSE 0 END) AS PRE_CAMPAIGN_SPEND,
        SUM(CASE WHEN t.DAY BETWEEN ch.END_DAY + 1 AND ch.END_DAY + ch.CAMPAIGN_DURATION_DAYS THEN t.SALES_VALUE ELSE 0 END) AS POST_CAMPAIGN_SPEND,
        SUM(CASE WHEN t.DAY BETWEEN ch.START_DAY AND ch.END_DAY THEN t.TOTAL_DISCOUNT ELSE 0 END) AS CAMPAIGN_DISCOUNT_GIVEN,
        COUNT(DISTINCT CASE WHEN t.DAY BETWEEN ch.START_DAY AND ch.END_DAY THEN t.BASKET_ID END) AS CAMPAIGN_VISITS
    FROM campaign_households ch
    JOIN {{ ref('stg_transactions') }} t ON ch.HOUSEHOLD_KEY = t.HOUSEHOLD_KEY
    GROUP BY 1, 2, 3, 4
),

coupon_redemptions AS (
    SELECT
        CAMPAIGN,
        COUNT(*) AS TOTAL_REDEMPTIONS,
        COUNT(DISTINCT HOUSEHOLD_KEY) AS UNIQUE_REDEEMERS
    FROM {{ source('raw', 'COUPON_REDEMPT') }}
    GROUP BY 1
)

SELECT
    ct.CAMPAIGN,
    ct.CAMPAIGN_TYPE,
    ct.CAMPAIGN_DURATION_DAYS,
    COUNT(DISTINCT ct.HOUSEHOLD_KEY) AS TARGETED_HOUSEHOLDS,
    COALESCE(cr.UNIQUE_REDEEMERS, 0) AS COUPON_REDEEMERS,
    CASE
        WHEN COUNT(DISTINCT ct.HOUSEHOLD_KEY) > 0
        THEN ROUND(COALESCE(cr.UNIQUE_REDEEMERS, 0)::FLOAT / COUNT(DISTINCT ct.HOUSEHOLD_KEY) * 100, 2)
        ELSE 0
    END AS REDEMPTION_RATE_PCT,
    ROUND(SUM(ct.PRE_CAMPAIGN_SPEND), 2) AS TOTAL_PRE_SPEND,
    ROUND(SUM(ct.DURING_CAMPAIGN_SPEND), 2) AS TOTAL_DURING_SPEND,
    ROUND(SUM(ct.POST_CAMPAIGN_SPEND), 2) AS TOTAL_POST_SPEND,
    ROUND(SUM(ct.CAMPAIGN_DISCOUNT_GIVEN), 2) AS TOTAL_DISCOUNT_GIVEN,
    CASE
        WHEN SUM(ct.PRE_CAMPAIGN_SPEND) > 0
        THEN ROUND((SUM(ct.DURING_CAMPAIGN_SPEND) - SUM(ct.PRE_CAMPAIGN_SPEND)) / SUM(ct.PRE_CAMPAIGN_SPEND) * 100, 2)
        ELSE NULL
    END AS SPEND_LIFT_PCT,
    CASE
        WHEN SUM(ct.CAMPAIGN_DISCOUNT_GIVEN) > 0
        THEN ROUND((SUM(ct.DURING_CAMPAIGN_SPEND) - SUM(ct.PRE_CAMPAIGN_SPEND)) / SUM(ct.CAMPAIGN_DISCOUNT_GIVEN), 2)
        ELSE NULL
    END AS CAMPAIGN_ROI,
    SUM(ct.CAMPAIGN_VISITS) AS TOTAL_CAMPAIGN_VISITS,
    ROUND(AVG(ct.DURING_CAMPAIGN_SPEND), 2) AS AVG_SPEND_PER_HOUSEHOLD
FROM campaign_txns ct
LEFT JOIN coupon_redemptions cr ON ct.CAMPAIGN = cr.CAMPAIGN
GROUP BY 1, 2, 3, cr.UNIQUE_REDEEMERS
