WITH weekly_product_metrics AS (
    SELECT
        t.PRODUCT_ID,
        p.DEPARTMENT,
        p.COMMODITY_DESC,
        p.BRAND,
        t.WEEK_NO,
        AVG(t.GROSS_PRICE / NULLIF(t.QUANTITY, 0)) AS AVG_UNIT_PRICE,
        SUM(t.QUANTITY) AS TOTAL_UNITS_SOLD,
        SUM(t.SALES_VALUE) AS TOTAL_REVENUE,
        AVG(t.TOTAL_DISCOUNT / NULLIF(t.QUANTITY, 0)) AS AVG_DISCOUNT_PER_UNIT,
        CASE
            WHEN AVG(t.GROSS_PRICE / NULLIF(t.QUANTITY, 0)) > 0
            THEN ROUND(AVG(t.TOTAL_DISCOUNT / NULLIF(t.QUANTITY, 0)) / AVG(t.GROSS_PRICE / NULLIF(t.QUANTITY, 0)) * 100, 2)
            ELSE 0
        END AS DISCOUNT_DEPTH_PCT
    FROM {{ ref('stg_transactions') }} t
    JOIN {{ ref('stg_products') }} p ON t.PRODUCT_ID = p.PRODUCT_ID
    GROUP BY 1, 2, 3, 4, 5
),

price_quantity_by_dept AS (
    SELECT
        DEPARTMENT,
        COMMODITY_DESC,
        AVG(AVG_UNIT_PRICE) AS AVG_PRICE,
        STDDEV(AVG_UNIT_PRICE) AS PRICE_STDDEV,
        AVG(TOTAL_UNITS_SOLD) AS AVG_UNITS,
        STDDEV(TOTAL_UNITS_SOLD) AS UNITS_STDDEV,
        COUNT(*) AS NUM_OBSERVATIONS,
        CORR(AVG_UNIT_PRICE, TOTAL_UNITS_SOLD) AS PRICE_QUANTITY_CORRELATION
    FROM weekly_product_metrics
    GROUP BY 1, 2
    HAVING COUNT(*) >= 10
)

SELECT
    DEPARTMENT,
    COMMODITY_DESC,
    ROUND(AVG_PRICE, 2) AS AVG_PRICE,
    ROUND(AVG_UNITS, 2) AS AVG_UNITS_SOLD,
    NUM_OBSERVATIONS,
    ROUND(PRICE_QUANTITY_CORRELATION, 4) AS PRICE_ELASTICITY_PROXY,
    CASE
        WHEN PRICE_QUANTITY_CORRELATION < -0.5 THEN 'Highly Elastic'
        WHEN PRICE_QUANTITY_CORRELATION < -0.2 THEN 'Moderately Elastic'
        WHEN PRICE_QUANTITY_CORRELATION < 0 THEN 'Low Elasticity'
        ELSE 'Inelastic / Positive'
    END AS ELASTICITY_CATEGORY
FROM price_quantity_by_dept
