WITH txn_with_promo AS (
    SELECT
        t.PRODUCT_ID,
        t.STORE_ID,
        t.WEEK_NO,
        t.HOUSEHOLD_KEY,
        t.BASKET_ID,
        t.QUANTITY,
        t.SALES_VALUE,
        t.TOTAL_DISCOUNT,
        t.GROSS_PRICE,
        t.IS_DISCOUNTED,
        COALESCE(c.HAS_DISPLAY, FALSE) AS HAS_DISPLAY,
        COALESCE(c.HAS_MAILER, FALSE) AS HAS_MAILER,
        COALESCE(c.IS_PROMOTED, FALSE) AS IS_PROMOTED,
        c.DISPLAY AS DISPLAY_TYPE,
        c.MAILER AS MAILER_TYPE
    FROM {{ ref('stg_transactions') }} t
    LEFT JOIN {{ ref('stg_causal') }} c
        ON t.PRODUCT_ID = c.PRODUCT_ID
        AND t.STORE_ID = c.STORE_ID
        AND t.WEEK_NO = c.WEEK_NO
),

product_week_agg AS (
    SELECT
        PRODUCT_ID,
        STORE_ID,
        WEEK_NO,
        IS_PROMOTED,
        HAS_DISPLAY,
        HAS_MAILER,
        DISPLAY_TYPE,
        MAILER_TYPE,
        COUNT(DISTINCT BASKET_ID) AS NUM_BASKETS,
        COUNT(DISTINCT HOUSEHOLD_KEY) AS NUM_HOUSEHOLDS,
        SUM(QUANTITY) AS TOTAL_UNITS,
        SUM(SALES_VALUE) AS TOTAL_REVENUE,
        SUM(TOTAL_DISCOUNT) AS TOTAL_DISCOUNT,
        SUM(GROSS_PRICE) AS TOTAL_GROSS_PRICE,
        AVG(SALES_VALUE) AS AVG_TRANSACTION_VALUE
    FROM txn_with_promo
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8
),

baseline AS (
    SELECT
        PRODUCT_ID,
        STORE_ID,
        AVG(CASE WHEN NOT IS_PROMOTED THEN TOTAL_UNITS END) AS BASELINE_UNITS,
        AVG(CASE WHEN NOT IS_PROMOTED THEN TOTAL_REVENUE END) AS BASELINE_REVENUE,
        AVG(CASE WHEN NOT IS_PROMOTED THEN NUM_HOUSEHOLDS END) AS BASELINE_HOUSEHOLDS
    FROM product_week_agg
    GROUP BY 1, 2
)

SELECT
    pwa.*,
    b.BASELINE_UNITS,
    b.BASELINE_REVENUE,
    b.BASELINE_HOUSEHOLDS,
    CASE
        WHEN b.BASELINE_UNITS > 0 THEN ROUND((pwa.TOTAL_UNITS - b.BASELINE_UNITS) / b.BASELINE_UNITS * 100, 2)
        ELSE NULL
    END AS UNIT_LIFT_PCT,
    CASE
        WHEN b.BASELINE_REVENUE > 0 THEN ROUND((pwa.TOTAL_REVENUE - b.BASELINE_REVENUE) / b.BASELINE_REVENUE * 100, 2)
        ELSE NULL
    END AS REVENUE_LIFT_PCT,
    pwa.TOTAL_UNITS - COALESCE(b.BASELINE_UNITS, 0) AS INCREMENTAL_UNITS,
    pwa.TOTAL_REVENUE - COALESCE(b.BASELINE_REVENUE, 0) AS INCREMENTAL_REVENUE
FROM product_week_agg pwa
LEFT JOIN baseline b
    ON pwa.PRODUCT_ID = b.PRODUCT_ID
    AND pwa.STORE_ID = b.STORE_ID
