WITH campaign_household_spend AS (
    SELECT
        cd.CAMPAIGN_ID,
        cd.CAMPAIGN_TYPE,
        cd.START_DAY,
        cd.END_DAY,
        cd.CAMPAIGN_DURATION_DAYS,
        ct.HOUSEHOLD_KEY,
        SUM(CASE
            WHEN t.DAY BETWEEN cd.START_DAY - cd.CAMPAIGN_DURATION_DAYS AND cd.START_DAY - 1
            THEN t.SALES_VALUE ELSE 0
        END) AS PRE_SPEND,
        SUM(CASE
            WHEN t.DAY BETWEEN cd.START_DAY AND cd.END_DAY
            THEN t.SALES_VALUE ELSE 0
        END) AS DURING_SPEND,
        SUM(CASE
            WHEN t.DAY BETWEEN cd.END_DAY + 1 AND cd.END_DAY + cd.CAMPAIGN_DURATION_DAYS
            THEN t.SALES_VALUE ELSE 0
        END) AS POST_SPEND
    FROM {{ ref('stg_campaigns') }} cd
    JOIN {{ source('raw', 'CAMPAIGN_TABLE') }} ct ON cd.CAMPAIGN_ID = ct.CAMPAIGN
    JOIN {{ ref('stg_transactions') }} t ON ct.HOUSEHOLD_KEY = t.HOUSEHOLD_KEY
    GROUP BY 1, 2, 3, 4, 5, 6
)

SELECT
    CAMPAIGN_ID,
    CAMPAIGN_TYPE,
    CAMPAIGN_DURATION_DAYS,
    COUNT(DISTINCT HOUSEHOLD_KEY) AS NUM_HOUSEHOLDS,
    ROUND(AVG(PRE_SPEND), 2) AS AVG_PRE_SPEND,
    ROUND(AVG(DURING_SPEND), 2) AS AVG_DURING_SPEND,
    ROUND(AVG(POST_SPEND), 2) AS AVG_POST_SPEND,
    ROUND(AVG(DURING_SPEND) - AVG(PRE_SPEND), 2) AS DURING_VS_PRE_DIFF,
    ROUND(AVG(POST_SPEND) - AVG(PRE_SPEND), 2) AS POST_VS_PRE_DIFF,
    CASE
        WHEN AVG(PRE_SPEND) > 0 THEN ROUND((AVG(DURING_SPEND) - AVG(PRE_SPEND)) / AVG(PRE_SPEND) * 100, 2)
        ELSE NULL
    END AS DURING_LIFT_PCT,
    CASE
        WHEN AVG(PRE_SPEND) > 0 THEN ROUND((AVG(POST_SPEND) - AVG(PRE_SPEND)) / AVG(PRE_SPEND) * 100, 2)
        ELSE NULL
    END AS POST_CHANGE_PCT,
    CASE
        WHEN AVG(PRE_SPEND) > 0 AND (AVG(POST_SPEND) - AVG(PRE_SPEND)) / AVG(PRE_SPEND) * 100 < -15
        THEN 'PANTRY LOADING (Post dip > 15%)'
        WHEN AVG(PRE_SPEND) > 0 AND (AVG(POST_SPEND) - AVG(PRE_SPEND)) / AVG(PRE_SPEND) * 100 < -5
        THEN 'MILD PULL-FORWARD (Post dip 5-15%)'
        WHEN AVG(PRE_SPEND) > 0 AND (AVG(POST_SPEND) - AVG(PRE_SPEND)) / AVG(PRE_SPEND) * 100 >= -5
        THEN 'TRUE DEMAND GENERATION (No post dip)'
        ELSE 'INSUFFICIENT DATA'
    END AS PANTRY_LOADING_FLAG
FROM campaign_household_spend
GROUP BY 1, 2, 3
