WITH promo_summary AS (
    SELECT
        IS_PROMOTED,
        HAS_DISPLAY,
        HAS_MAILER,
        DISPLAY_TYPE,
        MAILER_TYPE,
        COUNT(*) AS NUM_PRODUCT_STORE_WEEKS,
        SUM(TOTAL_UNITS) AS TOTAL_UNITS,
        SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
        SUM(TOTAL_DISCOUNT) AS TOTAL_DISCOUNT_GIVEN,
        SUM(INCREMENTAL_REVENUE) AS TOTAL_INCREMENTAL_REVENUE,
        SUM(INCREMENTAL_UNITS) AS TOTAL_INCREMENTAL_UNITS,
        AVG(UNIT_LIFT_PCT) AS AVG_UNIT_LIFT_PCT,
        AVG(REVENUE_LIFT_PCT) AS AVG_REVENUE_LIFT_PCT
    FROM {{ ref('mart_promo_effectiveness') }}
    GROUP BY 1, 2, 3, 4, 5
)

SELECT
    *,
    CASE
        WHEN TOTAL_DISCOUNT_GIVEN > 0 THEN ROUND(TOTAL_INCREMENTAL_REVENUE / TOTAL_DISCOUNT_GIVEN, 2)
        ELSE NULL
    END AS PROMO_ROI
FROM promo_summary
