WITH basket_items AS (
    SELECT
        t.BASKET_ID,
        t.HOUSEHOLD_KEY,
        t.STORE_ID,
        t.WEEK_NO,
        t.PRODUCT_ID,
        t.SALES_VALUE,
        t.TOTAL_DISCOUNT,
        t.IS_DISCOUNTED,
        COALESCE(c.IS_PROMOTED, FALSE) AS IS_PROMOTED_ITEM
    FROM {{ ref('stg_transactions') }} t
    LEFT JOIN {{ ref('stg_causal') }} c
        ON t.PRODUCT_ID = c.PRODUCT_ID
        AND t.STORE_ID = c.STORE_ID
        AND t.WEEK_NO = c.WEEK_NO
    WHERE t.IS_OUTLIER = FALSE
),

basket_summary AS (
    SELECT
        BASKET_ID,
        HOUSEHOLD_KEY,
        COUNT(DISTINCT PRODUCT_ID) AS BASKET_SIZE,
        SUM(SALES_VALUE) AS BASKET_TOTAL,
        SUM(CASE WHEN IS_PROMOTED_ITEM THEN SALES_VALUE ELSE 0 END) AS PROMOTED_ITEM_REVENUE,
        SUM(CASE WHEN NOT IS_PROMOTED_ITEM THEN SALES_VALUE ELSE 0 END) AS NON_PROMOTED_ITEM_REVENUE,
        SUM(CASE WHEN IS_PROMOTED_ITEM THEN 1 ELSE 0 END) AS PROMOTED_ITEMS_COUNT,
        SUM(CASE WHEN NOT IS_PROMOTED_ITEM THEN 1 ELSE 0 END) AS NON_PROMOTED_ITEMS_COUNT,
        MAX(CASE WHEN IS_PROMOTED_ITEM THEN 1 ELSE 0 END) AS HAS_PROMOTED_ITEM
    FROM basket_items
    GROUP BY 1, 2
)

SELECT
    CASE WHEN HAS_PROMOTED_ITEM = 1 THEN 'Contains Promo Item' ELSE 'No Promo Item' END AS BASKET_TYPE,
    COUNT(DISTINCT BASKET_ID) AS NUM_BASKETS,
    ROUND(AVG(BASKET_SIZE), 2) AS AVG_BASKET_SIZE,
    ROUND(AVG(BASKET_TOTAL), 2) AS AVG_BASKET_VALUE,
    ROUND(AVG(NON_PROMOTED_ITEM_REVENUE), 2) AS AVG_NON_PROMO_REVENUE_PER_BASKET,
    ROUND(AVG(NON_PROMOTED_ITEMS_COUNT), 2) AS AVG_NON_PROMO_ITEMS_PER_BASKET,
    ROUND(SUM(NON_PROMOTED_ITEM_REVENUE), 2) AS TOTAL_NON_PROMO_REVENUE,
    ROUND(SUM(BASKET_TOTAL), 2) AS TOTAL_BASKET_REVENUE
FROM basket_summary
GROUP BY 1
